# Rename this file to `secrets.yaml` and populate the values 
# below with your own secrets. Do not commit this file to source control.


# These values will be applied via Terraform to AWS Secrets Manager, and then read by the Lambda functions at runtime.
github:
  private_key_secret_value: |
    -----BEGIN RSA PRIVATE KEY-----
    ...
    -----END RSA PRIVATE KEY-----

webhook:
  secret_value: "..." # openssl rand -hex 32